$replacements = @(
    @{ file="Contactos\CambiarEtapaContacto.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n                await context.UpsertAgentContactActivityAsync(agenteId, id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Contactos\RevertirEstadoContacto.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n                    await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Contactos\FusionarContactos\FusionarContactos.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n                await context.UpsertAgentContactActivityAsync(agenteId, command.PrimaryId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Contactos\CompartirContacto.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentContactActivityAsync(agenteId, id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Contactos\RevocarCompartido.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Contactos\ToggleBotActivo.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Contactos\BotOverrideContacto.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Contactos\ToggleContactArchive.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    
    @{ file="Intereses\VincularPropiedad.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n                await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), contactoId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Intereses\DesvincularPropiedad.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), contactoId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Interacciones\ActualizarInteraccion.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), interaccion.ContactoId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Interacciones\EliminarInteraccion.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentContactActivityAsync(user.GetRequiredUserId(), interaccion.ContactoId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },

    @{ file="Propiedades\CambiarEstadoPropiedad.cs"; match="await context.SaveChangesAsync(CancellationToken.None);"; repl="await context.SaveChangesAsync(CancellationToken.None);`r`n                await context.UpsertAgentPropertyActivityAsync(currentUserId, request.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), CancellationToken.None);" },
    @{ file="Propiedades\TogglePropertyArchive.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Propiedades\VolverAListarPropiedad.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n                await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), id, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Propiedades\SubirImagenPropiedad.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n                await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), command.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Propiedades\EliminarImagenPropiedad.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n                await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), media.PropertyId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Propiedades\LimpiarImagenesPropiedad.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), command.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Propiedades\EliminarTodasLasImagenesPropiedad.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), command.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Propiedades\EliminarImagenesSeleccionadas.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), command.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Propiedades\EstablecerImagenPrincipal.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), command.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },

    @{ file="Faqs\CrearFaq.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), faq.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Faqs\EditarFaq.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), faq.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Faqs\AprobarFaq.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), faq.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Faqs\RechazarFaq.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), faq.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Faqs\ReactivarFaq.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), faq.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Faqs\DesactivarFaq.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), faq.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },

    @{ file="SeccionesGaleria\RegistrarSeccionGaleria.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), command.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="SeccionesGaleria\ActualizarSeccionGaleria.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), seccion.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="SeccionesGaleria\ReordenarSeccionesGaleria.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), command.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="SeccionesGaleria\EliminarSeccionGaleria.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), seccion.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="SeccionesGaleria\ActualizarDescripcionSeccion.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            await context.UpsertAgentPropertyActivityAsync(user.GetRequiredUserId(), seccion.PropiedadId, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },

    @{ file="Tareas\RegistrarTarea.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            if (tarea.ContactoId.HasValue) await context.UpsertAgentContactActivityAsync(agenteId, tarea.ContactoId.Value, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);`r`n            if (tarea.PropiedadId.HasValue) await context.UpsertAgentPropertyActivityAsync(agenteId, tarea.PropiedadId.Value, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Tareas\ActualizarTarea.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            if (tarea.ContactoId.HasValue) await context.UpsertAgentContactActivityAsync(agenteId, tarea.ContactoId.Value, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);`r`n            if (tarea.PropiedadId.HasValue) await context.UpsertAgentPropertyActivityAsync(agenteId, tarea.PropiedadId.Value, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" },
    @{ file="Tareas\CompletarTarea.cs"; match="await context.SaveChangesAsync(ct);"; repl="await context.SaveChangesAsync(ct);`r`n            if (tarea.ContactoId.HasValue) await context.UpsertAgentContactActivityAsync(agenteId, tarea.ContactoId.Value, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);`r`n            if (tarea.PropiedadId.HasValue) await context.UpsertAgentPropertyActivityAsync(agenteId, tarea.PropiedadId.Value, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), ct);" },
    @{ file="Tareas\CancelarTarea.cs"; match="await context.SaveChangesAsync();"; repl="await context.SaveChangesAsync();`r`n            if (tarea.ContactoId.HasValue) await context.UpsertAgentContactActivityAsync(agenteId, tarea.ContactoId.Value, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);`r`n            if (tarea.PropiedadId.HasValue) await context.UpsertAgentPropertyActivityAsync(agenteId, tarea.PropiedadId.Value, DateTimeOffset.UtcNow.ToOffset(TimeSpan.FromHours(-5)), default);" }
)

foreach ($r in $replacements) {
    if (Test-Path $r.file) {
        $content = Get-Content -Path $r.file -Raw
        if ($content -notmatch "UpsertAgent") {
            if ($content.Contains($r.match)) {
                $content = $content.Replace($r.match, $r.repl)
                Set-Content -Path $r.file -Value $content
                Write-Host "Updated $($r.file)"
            } else {
                Write-Host "Warning: Match not found in $($r.file)"
            }
        } else {
            Write-Host "Skipped $($r.file) (Already injected)"
        }
    } else {
        Write-Host "Error: File not found $($r.file)"
    }
}
