// <auto-generated />
using System;
using CRM_Inmobiliario.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM_Inmobiliario.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260503225129_AddCreatedByToProperty")]
    partial class AddCreatedByToProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AgenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AiActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TriggerMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelefonoContacto", "Fecha")
                        .HasDatabaseName("IX_AiActionLogs_TelefonoFecha");

                    b.ToTable("AiActionLogs");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EsPropietario")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsProspecto")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoPropietario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EtapaEmbudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId", "EtapaEmbudo", "FechaCierre", "FechaCreacion")
                        .HasDatabaseName("IX_Contactos_Performance_AgenteEtapaFecha");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactoInteresPropiedad", b =>
                {
                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelInteres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ContactoId", "PropiedadId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("ContactoInteresPropiedades");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaInteraccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoInteraccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("ContactoId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AniosAntiguedad")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AreaConstruccion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AreaTerreno")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AreaTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Banos")
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid?>("CerradoConId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedByAgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EsCaptacionPropia")
                        .HasColumnType("boolean");

                    b.Property<int?>("Estacionamientos")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoComercial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("text");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("integer");

                    b.Property<int?>("MediosBanos")
                        .HasColumnType("integer");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PorcentajeComision")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("PrecioCierre")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("PropietarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoPropiedad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UrlRemax")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CerradoConId");

                    b.HasIndex("CreatedByAgenteId");

                    b.HasIndex("PropietarioId");

                    b.HasIndex("AgenteId", "EstadoComercial", "EsCaptacionPropia", "FechaIngreso")
                        .HasDatabaseName("IX_Properties_Performance_AgenteEstadoCaptacion");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyGallerySection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.ToTable("PropertyGallerySections");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TipoMultimedia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UrlPublica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("SectionId");

                    b.ToTable("PropertyMedia");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PropertyId", "TransactionDate")
                        .HasDatabaseName("IX_PropertyTransactions_PropertyDate");

                    b.ToTable("PropertyTransactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lugar")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoTarea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("AgenteId", "Estado", "TipoTarea", "FechaInicio")
                        .HasDatabaseName("IX_Tasks_Performance_AgenteEstadoTipoFecha");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.WhatsappConversation", b =>
                {
                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("HistorialJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Telefono");

                    b.ToTable("WhatsappConversations");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.WhatsappMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Telefono", "Fecha")
                        .HasDatabaseName("IX_WhatsappMessages_TelefonoFecha");

                    b.ToTable("WhatsappMessages");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agent", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agency", "Agencia")
                        .WithMany("Agents")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("Agencia");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Contacto", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Contactos")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactoInteresPropiedad", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("PropertyInterests")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("ContactInterests")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Interactions")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("Interactions")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Interactions")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agente");

                    b.Navigation("Contacto");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agency", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Properties")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "CerradoCon")
                        .WithMany()
                        .HasForeignKey("CerradoConId");

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "CreatedByAgente")
                        .WithMany()
                        .HasForeignKey("CreatedByAgenteId");

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Propietario")
                        .WithMany("PropertiesOwned")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agencia");

                    b.Navigation("Agente");

                    b.Navigation("CerradoCon");

                    b.Navigation("CreatedByAgente");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyGallerySection", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("GallerySections")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyMedia", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Media")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.PropertyGallerySection", "Section")
                        .WithMany("Media")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Propiedad");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyTransaction", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("Transactions")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Property")
                        .WithMany("Transactions")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");

                    b.Navigation("CreatedBy");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Tasks")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("Tasks")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Tasks")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agente");

                    b.Navigation("Contacto");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agency", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("Interactions");

                    b.Navigation("Properties");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Contacto", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("PropertiesOwned");

                    b.Navigation("PropertyInterests");

                    b.Navigation("Tasks");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.Navigation("ContactInterests");

                    b.Navigation("GallerySections");

                    b.Navigation("Interactions");

                    b.Navigation("Media");

                    b.Navigation("Tasks");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyGallerySection", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
