// <auto-generated />
using System;
using CRM_Inmobiliario.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CRM_Inmobiliario.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260328133854_PermitirRelacionesOpcionalesEnPropiedades")]
    partial class PermitirRelacionesOpcionalesEnPropiedades
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaInteraccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoInteraccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EtapaEmbudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.LeadPropertyInterest", b =>
                {
                    b.Property<Guid>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelInteres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ClienteId", "PropiedadId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("LeadPropertyInterests");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AreaTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Banos")
                        .HasColumnType("decimal(3,1)");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("EstadoComercial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("integer");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("PrecioCierre")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("PropietarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoPropiedad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("PropietarioId");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TipoMultimedia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UrlPublica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.ToTable("PropertyMedia");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("FechaVencimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoTarea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Interactions")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Lead", "Cliente")
                        .WithMany("Interactions")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Interactions")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agente");

                    b.Navigation("Cliente");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Lead", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Leads")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.LeadPropertyInterest", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Lead", "Cliente")
                        .WithMany("PropertyInterests")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("LeadInterests")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Properties")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Lead", "Propietario")
                        .WithMany("PropertiesOwned")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agente");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyMedia", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Media")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Tasks")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Lead", "Cliente")
                        .WithMany("Tasks")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Tasks")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agente");

                    b.Navigation("Cliente");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("Leads");

                    b.Navigation("Properties");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Lead", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("PropertiesOwned");

                    b.Navigation("PropertyInterests");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.Navigation("Interactions");

                    b.Navigation("LeadInterests");

                    b.Navigation("Media");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
