// <auto-generated />
using System;
using CRM_Inmobiliario.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CRM_Inmobiliario.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CrmDbContext))]
    [Migration("20260613005927_AddAgentContextFields")]
    partial class AddAgentContextFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContextoCorporativoIA")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DireccionFisica")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EmailCorporativo")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("SitioWeb")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TelefonoCorporativo")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Agencies");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActiveLLMProvider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("AgenciaId")
                        .HasColumnType("uuid");

                    b.Property<string>("AiApiKey")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AutoCreateFacebookContacts")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoCreateWhatsAppContacts")
                        .HasColumnType("boolean");

                    b.Property<string>("ByokKeyStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Valid")
                        .HasColumnName("byok_key_status");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<int>("DailyTokenLimitFacebook")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTokenLimitPerContact")
                        .HasColumnType("integer");

                    b.Property<int>("DailyTokenLimitPersonal")
                        .HasColumnType("integer");

                    b.Property<string>("DireccionFisica")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FacebookPageAccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FacebookPageId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FacebookPageName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsFacebookAiEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPersonalAiEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsWhatsAppAiEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromptPersonalIA")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("WhatsAppPhoneNumberId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentConversations");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentDailyTokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AhorroUSD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m);

                    b.Property<int>("CachedTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CostoUSD")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18, 6)")
                        .HasDefaultValue(0m);

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("OutputTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "Date")
                        .IsUnique();

                    b.ToTable("AgentDailyTokenUsages", (string)null);
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentConversationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("AgentConversationId");

                    b.ToTable("AgentMessages");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentPushSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.ToTable("AgentPushSubscriptions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AiActionLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("DetalleJson")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TelefonoContacto")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TriggerMessage")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TelefonoContacto", "Fecha")
                        .HasDatabaseName("IX_AiActionLogs_TelefonoFecha");

                    b.ToTable("AiActionLogs");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactDailyTokenUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("AhorroUSD")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("CachedTokens")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CostoUSD")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("OutputTokens")
                        .HasColumnType("integer");

                    b.Property<int>("TokensUsed")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId", "Date", "Channel")
                        .IsUnique();

                    b.ToTable("ContactDailyTokenUsages");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Apellido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("BotActivoFB")
                        .HasColumnType("boolean");

                    b.Property<bool>("BotActivoWA")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EsPropietario")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsProspecto")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoIA_FB")
                        .HasColumnType("text");

                    b.Property<string>("EstadoIA_WA")
                        .HasColumnType("text");

                    b.Property<string>("EstadoPropietario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EtapaEmbudo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FacebookSenderId")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NormalizedSearchText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("NumeroCierres")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroInteracciones")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroIntereses")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroPropiedadesCaptadas")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroReservas")
                        .HasColumnType("integer");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TransferenciaNotificada")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedSearchText")
                        .HasDatabaseName("idx_contactos_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedSearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedSearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Telefono", "AgenteId")
                        .IsUnique();

                    b.HasIndex("AgenteId", "EtapaEmbudo", "FechaCierre", "FechaCreacion")
                        .HasDatabaseName("IX_Contactos_Performance_AgenteEtapaFecha");

                    b.ToTable("Contactos");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactoAgenteCompartido", b =>
                {
                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaCompartido")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ContactoId", "AgenteId");

                    b.HasIndex("AgenteId");

                    b.ToTable("ContactoAgenteCompartidos", (string)null);
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactoHistorialEmbudo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("EtapaAnterior")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EtapaNueva")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("FechaCambio")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.ToTable("ContactoHistorialEmbudos");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactoInteresPropiedad", b =>
                {
                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NivelInteres")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("ContactoId", "PropiedadId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("ContactoInteresPropiedades");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenciaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenciaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Audience")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(1536)");

                    b.Property<Vector>("GeminiEmbedding")
                        .HasColumnType("vector(768)");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("Embedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("GeminiEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("GeminiEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("GeminiEmbedding"), new[] { "vector_cosine_ops" });

                    b.ToTable("DocumentChunks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.FacebookConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("FacebookSenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("HistorialJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PageId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FacebookConversations");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.FacebookMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookSenderId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FacebookMessages");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Interaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("FechaInteraccion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoInteraccion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("ContactoId");

                    b.HasIndex("PropiedadId");

                    b.ToTable("Interactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenciaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenteCerradorId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<int?>("AniosAntiguedad")
                        .HasColumnType("integer");

                    b.Property<decimal?>("AreaConstruccion")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("AreaTerreno")
                        .HasColumnType("numeric");

                    b.Property<decimal>("AreaTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Banos")
                        .HasColumnType("decimal(3,1)");

                    b.Property<Guid?>("CerradoConId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("CreatedByAgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<bool>("EsCaptacionPropia")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsCaptadorActivo")
                        .HasColumnType("boolean");

                    b.Property<int?>("Estacionamientos")
                        .HasColumnType("integer");

                    b.Property<string>("EstadoComercial")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset?>("FechaCierre")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaIngreso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Vector>("GeminiEmbedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("GoogleMapsUrl")
                        .HasColumnType("text");

                    b.Property<int>("Habitaciones")
                        .HasColumnType("integer");

                    b.Property<int?>("MediosBanos")
                        .HasColumnType("integer");

                    b.Property<string>("NormalizedSearchText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Operacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("PorcentajeComision")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("PrecioCierre")
                        .HasColumnType("decimal(12,2)");

                    b.Property<decimal?>("PrecioReserva")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("PropietarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TipoPropiedad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UrlRemax")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Vector>("VectorEmbedding")
                        .HasColumnType("vector(1536)");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("AgenciaId");

                    b.HasIndex("AgenteCerradorId");

                    b.HasIndex("CerradoConId");

                    b.HasIndex("CreatedByAgenteId");

                    b.HasIndex("GeminiEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("GeminiEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("GeminiEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("NormalizedSearchText")
                        .HasDatabaseName("idx_properties_search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("NormalizedSearchText"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("NormalizedSearchText"), new[] { "gin_trgm_ops" });

                    b.HasIndex("PropietarioId");

                    b.HasIndex("VectorEmbedding");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("VectorEmbedding"), "hnsw");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("VectorEmbedding"), new[] { "vector_cosine_ops" });

                    b.HasIndex("AgenteId", "EstadoComercial", "EsCaptacionPropia", "FechaIngreso")
                        .HasDatabaseName("IX_Properties_Performance_AgenteEstadoCaptacion");

                    b.ToTable("Properties");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyGallerySection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.ToTable("PropertyGallerySections");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyMedia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsPrincipal")
                        .HasColumnType("boolean");

                    b.Property<int>("Orden")
                        .HasColumnType("integer");

                    b.Property<Guid>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SectionId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("TipoMultimedia")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("UrlPublica")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("SectionId");

                    b.ToTable("PropertyMedia");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PropertyId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("PropertyId", "TransactionDate")
                        .HasDatabaseName("IX_PropertyTransactions_PropertyDate");

                    b.ToTable("PropertyTransactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.SecurityAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TipoIncidente")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgenteId");

                    b.HasIndex("Timestamp");

                    b.ToTable("SecurityAuditLogs", (string)null);
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgenteId")
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Lugar")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("PropiedadId")
                        .HasColumnType("uuid");

                    b.Property<string>("TipoTarea")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("PropiedadId");

                    b.HasIndex("AgenteId", "Estado", "TipoTarea", "FechaInicio")
                        .HasDatabaseName("IX_Tasks_Performance_AgenteEstadoTipoFecha");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.WhatsappConversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("HistorialJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTimeOffset>("UltimaActualizacion")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.ToTable("WhatsappConversations");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.WhatsappMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ContactoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contenido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("ContactoId");

                    b.HasIndex("Telefono", "Fecha")
                        .HasDatabaseName("IX_WhatsappMessages_TelefonoFecha");

                    b.ToTable("WhatsappMessages");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agent", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agency", "Agencia")
                        .WithMany("Agents")
                        .HasForeignKey("AgenciaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("Agencia");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentConversation", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentDailyTokenUsage", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentMessage", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.AgentConversation", "AgentConversation")
                        .WithMany("Messages")
                        .HasForeignKey("AgentConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentConversation");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentPushSubscription", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agent")
                        .WithMany("PushSubscriptions")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactDailyTokenUsage", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Contacto", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Contactos")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactoAgenteCompartido", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("ContactosCompartidos")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("CompartidoCon")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactoHistorialEmbudo", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("HistorialEmbudo")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.ContactoInteresPropiedad", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("PropertyInterests")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("ContactInterests")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Document", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agency", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.Navigation("Agencia");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.DocumentChunk", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agency", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agencia");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Interaction", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Interactions")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("Interactions")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Interactions")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agente");

                    b.Navigation("Contacto");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agency", "Agencia")
                        .WithMany()
                        .HasForeignKey("AgenciaId");

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "AgenteCerrador")
                        .WithMany()
                        .HasForeignKey("AgenteCerradorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Properties")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "CerradoCon")
                        .WithMany("PropertiesClosed")
                        .HasForeignKey("CerradoConId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "CreatedByAgente")
                        .WithMany()
                        .HasForeignKey("CreatedByAgenteId");

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Propietario")
                        .WithMany("PropertiesOwned")
                        .HasForeignKey("PropietarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Agencia");

                    b.Navigation("Agente");

                    b.Navigation("AgenteCerrador");

                    b.Navigation("CerradoCon");

                    b.Navigation("CreatedByAgente");

                    b.Navigation("Propietario");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyGallerySection", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("GallerySections")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyMedia", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Media")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.PropertyGallerySection", "Section")
                        .WithMany("Media")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Propiedad");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyTransaction", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("Transactions")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Property")
                        .WithMany("Transactions")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");

                    b.Navigation("CreatedBy");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.SecurityAuditLog", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany()
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agente");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.TaskItem", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Agent", "Agente")
                        .WithMany("Tasks")
                        .HasForeignKey("AgenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany("Tasks")
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Property", "Propiedad")
                        .WithMany("Tasks")
                        .HasForeignKey("PropiedadId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agente");

                    b.Navigation("Contacto");

                    b.Navigation("Propiedad");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.WhatsappConversation", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.WhatsappMessage", b =>
                {
                    b.HasOne("CRM_Inmobiliario.Api.Domain.Entities.Contacto", "Contacto")
                        .WithMany()
                        .HasForeignKey("ContactoId");

                    b.Navigation("Contacto");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agency", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Contactos");

                    b.Navigation("ContactosCompartidos");

                    b.Navigation("Interactions");

                    b.Navigation("Properties");

                    b.Navigation("PushSubscriptions");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.AgentConversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Contacto", b =>
                {
                    b.Navigation("CompartidoCon");

                    b.Navigation("HistorialEmbudo");

                    b.Navigation("Interactions");

                    b.Navigation("PropertiesClosed");

                    b.Navigation("PropertiesOwned");

                    b.Navigation("PropertyInterests");

                    b.Navigation("Tasks");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.Property", b =>
                {
                    b.Navigation("ContactInterests");

                    b.Navigation("GallerySections");

                    b.Navigation("Interactions");

                    b.Navigation("Media");

                    b.Navigation("Tasks");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("CRM_Inmobiliario.Api.Domain.Entities.PropertyGallerySection", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
