@HostAddress = http://localhost:5164

### Registrar un nuevo cliente (Prospecto)
POST {{HostAddress}}/api/clientes
Content-Type: application/json

{
  "nombre": "Juan",
  "apellido": "Pérez",
  "email": "juan.perez@ejemplo.com",
  "telefono": "+593987654321",
  "origen": "Facebook Ads"
}

###
